import { Product } from './types';

export const AICHA_WHATSAPP_NUMBER = '+212675020809';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Gel d\'Aloe Vera Stabilisé',
    nameAr: 'جل الألوفيرا المستقر',
    price: 295,
    description: 'Gel pur de feuille d\'aloe vera à 99.7%. Soutient la digestion, renforce le système immunitaire et apporte une vitalité naturelle au quotidien.',
    descriptionAr: 'جل نقي 99.7% من أوراق الألوفيرا. يدعم الهضم، يقوي الجهاز المناعي ويمنحك حيوية طبيعية يومية.',
    category: 'Aloe Vera',
    categoryAr: 'الألوفيرا',
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800',
    isBestseller: true,
  },
  {
    id: '2',
    name: 'Pollen d\'Abeille Pure Nature',
    nameAr: 'حبوب لقاح النحل الطبيعية',
    price: 220,
    description: 'Énergie 100% naturelle directement de la ruche. Riche en vitamines et minéraux pour l\'endurance et la vitalité.',
    descriptionAr: 'طاقة طبيعية 100% مباشرة من الخلية. غنية بالفيامينات والمعادن لتعزيز التحمل والحيوية.',
    category: 'Produits d\'Abeille',
    categoryAr: 'منتجات النحل',
    imageUrl: 'https://images.unsplash.com/photo-1587049352847-4a222e784d38?auto=format&fit=crop&q=80&w=800',
    isBestseller: true,
  },
  {
    id: '3',
    name: 'Forever Bright Toothgel',
    nameAr: 'معجون الأسنان فوريفير برايت',
    price: 110,
    description: 'Formule douce sans fluor à l\'aloès et propolis d\'abeille. Nettoie en profondeur et protège les gencives de toute la famille.',
    descriptionAr: 'تركيبة لطيفة خالية من الفلورايد مع الألوفيرا وعكبر النحل. ينظف بعمق ويحمي لثة جميع أفراد العائلة.',
    category: 'Soins Personnels',
    categoryAr: 'العناية الشخصية',
    imageUrl: 'https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&q=80&w=800',
    isBestseller: true,
  },
  {
    id: '4',
    name: 'Aloe Lips au Jojoba',
    nameAr: 'مرطب الشفاه بالألوفيرا والجوجوبا',
    price: 55,
    description: 'Baume apaisant et nourrissant pour les lèvres à l\'aloe vera, cire d\'abeille et huile de jojoba. Protection toute saison.',
    descriptionAr: 'بلسم مهدئ ومغذي للشفاه بالألوفيرا وشمع النحل وزيت الجوجوبا. حماية طوال الفصول.',
    category: 'Soins Personnels',
    categoryAr: 'العناية الشخصية',
    imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '5',
    name: 'Forever Berry Nectar',
    nameAr: 'رحيق الألوفيرا والتوت البري',
    price: 295,
    description: 'Bienfaits de l\'aloe vera alliés au goût savoureux de la canneberge et de la pomme. Riche en antioxydants.',
    descriptionAr: 'فوائد الألوفيرا مع طعم التوت البري والتفاح اللذيذ. غني بمضادات الأكسدة للصحة والمناعة.',
    category: 'Aloe Vera',
    categoryAr: 'الألوفيرا',
    imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '6',
    name: 'Forever Arctic Sea (Oméga 3)',
    nameAr: 'أوميغا 3 فوريفير آركتيك سي',
    price: 360,
    description: 'Mélange exclusif d\'acides gras Oméga-3 (huiles de poisson et de calamar) enrichi en huile d\'olive pour le cœur et le cerveau.',
    descriptionAr: 'مزيج حصري من حمض أوميغا 3 وزيت الزيتون لدعم صحة القلب والذكريات والجهاز العصبي.',
    category: 'Nutrition & Santé',
    categoryAr: 'التغذية والصحة',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800',
    isBestseller: true,
  },
  {
    id: '7',
    name: 'Crème Aloès & Propolis',
    nameAr: 'كريم الألوفيرا والبروبوليس',
    price: 245,
    description: 'Soin apaisant exceptionnel pour les peaux sèches et irritées. Combine l\'aloe vera stabilisé et la propolis d\'abeille.',
    descriptionAr: 'عناية فائقة ومهدئة للبشرة الجافة والمتهيجة. يجمع بين جل الألوفيرا وبروبوليس النحل.',
    category: 'Soins de la Peau',
    categoryAr: 'العناية بالبشرة',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '8',
    name: 'Forever Kids Multivitamines',
    nameAr: 'فيتامينات للأطفال فوريفير كيدز',
    price: 185,
    description: 'Comprimés à croquer savoureux fournissant les vitamines et minéraux essentiels au développement sain des enfants.',
    descriptionAr: 'أقراص مضغ لذيذة تمد الأطفال بالفيتامينات والمعادن الأساسية للنمو والنشاط اليومي.',
    category: 'Nutrition & Santé',
    categoryAr: 'التغذية والصحة',
    imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&q=80&w=800',
  },
];
